member: [TRELLO USER ID GOES HERE]
key: [TRELLO USER KEY GOES HERE SEE: http://www.rubydoc.info/gems/ruby-trello/Trello]
token: [TRELLO TOKEN GOES HERE SEE: http://www.rubydoc.info/gems/ruby-trello/Trello]
datadir: [LOCAL DIRECTORY YOU WANT DATA SAVED TO]
daily_cfd_schedule: 0 0 * * *
boards:
   -
      name: [TRELLO BOARD YOU WANT TRACKED]
      type: kanban
      exclude_columns: [LIST OF COLUMNS BY NAMES TO IGNORE]
      lead_time:
         start: 'created_date'
         end: [NAME OF COLUMN ON BOARD THAT MARKS 'DONE' STATE]
      cycle_time:
         start: [NAME OF COLUMN ON BOARD THAT MARKS THE START OF WORK ON A CARD]
         end: [NAME OF COLUMN ON BOARD THAT MARKS 'DONE' STATE]
      graphdef:
         element: 'uv-div'
         xkey: 'date_time'
         hideHover: 'auto'
         resize: true
         lineColors: ['green', 'yellow', 'red', 'grey', 'blue']
         parseTime: false
   -
      name: [TRELLO BOARD YOU WANT TRACKED]
      type: scrum
      exclude_columns: [LIST OF COLUMNS BY NAMES TO IGNORE]
      iteration:
         start_day: [DAY OF WEEK IN INTEGER 0-6 WHERE 0 IS SUNDAY]
         length: [NUMBER OF DAYS PER ITERATION]
      delimiter:
         start: [DELIMITER START SURROUNDED BY '' SUCH AS '(']
         end: [DELIMITER END SURROUNDED BY '' SUCH AS '(']
      graphdef:
         element: 'uv-div'
         xkey: 'date_time'
         hideHover: 'auto'
         resize: true
         lineColors: ['green', 'yellow', 'red', 'grey', 'blue']
         parseTime: false